import React, { useState } from 'react'

const LEVEL_COLORS = {
  '1A': 'text-emerald-700 bg-emerald-50 border-emerald-200',
  '1B': 'text-blue-700 bg-blue-50 border-blue-200',
  '2A': 'text-yellow-700 bg-yellow-50 border-yellow-200',
  '2B': 'text-orange-700 bg-orange-50 border-orange-200',
  '3':  'text-purple-700 bg-purple-50 border-purple-200',
  '4':  'text-gray-600 bg-gray-100 border-gray-200',
}

function Section({ title, icon, children }) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-lg">{icon}</span>
        <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wider">{title}</h3>
      </div>
      {children}
    </div>
  )
}

function RecommendationRow({ rec, index, onCiteClick }) {
  const levelClass = LEVEL_COLORS[rec.evidence_level] || LEVEL_COLORS['4']
  return (
    <div className="flex gap-3 p-4 rounded-lg bg-gray-50 border border-gray-100 mb-2">
      <div className="flex-shrink-0 w-7 h-7 rounded-full bg-blue-100 text-blue-600
                      flex items-center justify-center text-sm font-bold">
        {index + 1}
      </div>
      <div className="flex-1">
        <p className="text-sm text-gray-900 font-medium mb-1">{rec.recommendation}</p>
        {rec.rationale && (
          <p className="text-xs text-gray-500">{rec.rationale}</p>
        )}
        {/* Citation badges */}
        {rec.source_refs?.length > 0 && (
          <div className="flex flex-wrap gap-1 mt-2">
            {rec.source_refs.map((ref) => (
              <button
                key={ref}
                onClick={() => onCiteClick?.(ref - 1)}
                className="inline-flex items-center px-1.5 py-0.5 rounded text-xs font-mono font-semibold
                           bg-blue-100 text-blue-700 hover:bg-blue-200 hover:text-blue-900
                           border border-blue-200 transition-all duration-150"
                title={`Jump to source ${ref}`}
              >
                [{ref}]
              </button>
            ))}
          </div>
        )}
      </div>
      {rec.evidence_level && (
        <span className={`
          flex-shrink-0 self-start text-xs font-semibold px-2 py-0.5 rounded border
          ${levelClass}
        `}>
          {rec.evidence_level}
        </span>
      )}
    </div>
  )
}

function InterventionTag({ item }) {
  const levelClass = LEVEL_COLORS[item.evidence_level] || LEVEL_COLORS['4']
  return (
    <div className="flex items-start gap-3 p-3 rounded-lg bg-gray-50 border border-gray-100 mb-2">
      <span className={`
        flex-shrink-0 text-xs font-semibold px-2 py-0.5 rounded border mt-0.5
        ${levelClass}
      `}>
        {item.evidence_level || '?'}
      </span>
      <div>
        <p className="text-sm font-medium text-gray-900">{item.name}</p>
        {item.summary && <p className="text-xs text-gray-500 mt-0.5">{item.summary}</p>}
      </div>
    </div>
  )
}

export default function ReportPanel({ report, question, onCiteClick }) {
  const [copied, setCopied] = useState(false)

  if (!report) return null

  const reportText = `CLINICALMIND CLINICAL EVIDENCE REPORT
=====================================
Clinical Question: ${question}

BACKGROUND
${report.background || 'N/A'}

KEY INTERVENTIONS
${(report.key_interventions || []).map((i, n) => `${n+1}. [${i.evidence_level}] ${i.name}: ${i.summary}`).join('\n')}

EVIDENCE SUMMARY
${report.evidence_summary || 'N/A'}

RECOMMENDATIONS
${(report.recommendations || []).map((r, n) => `${n+1}. [${r.evidence_level}] ${r.recommendation}\n   Rationale: ${r.rationale}`).join('\n\n')}

CLINICAL BOTTOM LINE
${report.clinical_bottom_line || 'N/A'}

LIMITATIONS
${report.limitations || 'N/A'}

Generated by ClinicalMind — AI Clinical Evidence Synthesis
`

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (e) {
      console.error('Copy failed', e)
    }
  }

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `ClinicalMind_Report_${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden
                    animate-slide-up opacity-0"
         style={{ animationFillMode: 'forwards' }}>
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-100
                      bg-gradient-to-r from-blue-50 to-purple-50/40
                      flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold text-gray-900 flex items-center gap-2">
            <svg className="w-4 h-4 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round"
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Clinical Evidence Report
          </h2>
          <p className="text-xs text-gray-500 mt-0.5 line-clamp-1">
            {question}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
                       bg-white hover:bg-gray-50 text-gray-600 hover:text-gray-900
                       border border-gray-200 transition-all duration-200 shadow-sm"
          >
            {copied
              ? <><span>✓</span> Copied</>
              : <><svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg> Copy</>
            }
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
                       bg-blue-600 hover:bg-blue-700 text-white
                       border border-blue-600 transition-all duration-200 shadow-sm"
          >
            <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round"
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download
          </button>
        </div>
      </div>

      {/* Body */}
      <div className="p-6">
        {/* Clinical Bottom Line */}
        {report.clinical_bottom_line && (
          <div className="mb-6 p-4 rounded-xl bg-blue-50 border border-blue-200">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-blue-600">⚡</span>
              <span className="text-xs font-semibold text-blue-700 uppercase tracking-wider">
                Clinical Bottom Line
              </span>
            </div>
            <p className="text-sm text-gray-900 font-medium leading-relaxed">
              {report.clinical_bottom_line}
            </p>
          </div>
        )}

        {/* Background */}
        {report.background && (
          <Section title="Background" icon="📖">
            <p className="text-sm text-gray-700 leading-relaxed">{report.background}</p>
          </Section>
        )}

        {/* Key Interventions */}
        {report.key_interventions?.length > 0 && (
          <Section title="Key Interventions" icon="💊">
            {report.key_interventions.map((item, i) => (
              <InterventionTag key={i} item={item} />
            ))}
          </Section>
        )}

        {/* Evidence Summary */}
        {report.evidence_summary && (
          <Section title="Evidence Summary" icon="📊">
            <div className="prose prose-sm max-w-none">
              {report.evidence_summary.split('\n').filter(Boolean).map((para, i) => (
                <p key={i} className="text-sm text-gray-700 leading-relaxed mb-2">{para}</p>
              ))}
            </div>
          </Section>
        )}

        {/* Recommendations */}
        {report.recommendations?.length > 0 && (
          <Section title="Recommendations" icon="✅">
            {report.recommendations.map((rec, i) => (
              <RecommendationRow key={i} rec={rec} index={i} onCiteClick={onCiteClick} />
            ))}
          </Section>
        )}

        {/* Limitations */}
        {report.limitations && (
          <Section title="Limitations" icon="⚠️">
            <div className="p-3 rounded-lg bg-amber-50 border border-amber-200">
              <p className="text-sm text-amber-900 leading-relaxed">{report.limitations}</p>
            </div>
          </Section>
        )}

        {/* Footer */}
        <div className="mt-6 pt-4 border-t border-gray-100 flex items-center justify-between">
          <p className="text-xs text-gray-400">
            Generated by ClinicalMind · AI Clinical Evidence Synthesis
          </p>
          <p className="text-xs text-gray-400">
            {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
          </p>
        </div>
      </div>
    </div>
  )
}
